# Generated by Django 5.0.2 on 2024-02-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Performance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("performance_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("date_from", models.CharField(max_length=20)),
                ("date_to", models.CharField(max_length=20)),
                ("faculty_id", models.CharField(max_length=20)),
                ("faculty_name", models.CharField(max_length=255)),
                ("poster", models.CharField(max_length=255)),
                ("area", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                ("story", models.TextField()),
                ("enterprise_p", models.CharField(max_length=255)),
                ("enterprise_a", models.CharField(max_length=255)),
                ("enterprise_h", models.CharField(max_length=255)),
                ("enterprise_s", models.CharField(max_length=255)),
                ("seats", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "performance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PerformanceDatetime",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("performance_id", models.CharField(max_length=20)),
                ("day", models.CharField(max_length=20)),
                ("time", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "performance_datetime",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PerformancePerson",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("performance_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "performance_person",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PerformancePrice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("performance_id", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "performance_price",
                "managed": False,
            },
        ),
    ]
